# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'jpHacks2018-team-toralab' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Socket.IO-Client-Swift', '~> 13.3.0'
  # Pods for jpHacks2018-team-toralab
end
